import Link from "next/link";
import {
  ZODIAC_ELEMENTS,
  getAstrologyByElement,
} from "@/data/astrology/archetypes";
import { buildPageMetadata } from "@/lib/site";
import BlindSpotsSection from "@/components/shared/BlindSpotsSection";
import ZodiacGlyph from "@/components/ZodiacGlyph";

export const metadata = buildPageMetadata({
  title: "About - Astrology",
  description:
    "The tropical zodiac read as projected psychology: twelve character structures generated by four elements and three modalities - with astrology's empirical failures stated plainly, and the case for hosting it anyway.",
  path: "/astrology/about",
});

export default function AstrologyAbout() {
  return (
    <div className="min-h-screen px-6 pt-24 pb-20 md:pt-32">
      <div className="max-w-3xl mx-auto">
        <p className="font-mono text-kicker tracking-display text-gold/80 uppercase mb-4 animate-slide-up">
          About the System
        </p>
        <h1 className="font-serif text-4xl sm:text-5xl md:text-6xl font-medium text-text-primary tracking-tight leading-display mb-10 animate-slide-up">
          Written in Us,{" "}
          <span className="text-gold glow-text-subtle">Not the Stars</span>
        </h1>

        <div className="space-y-8 text-text-secondary leading-relaxed font-light animate-slide-up delay-200">
          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              What Astrology Is Here
            </h2>
            <p className="mb-4">
              The tropical zodiac is a wheel of twelve signs, generated by a
              small grammar: four elements crossed with three modalities. It is
              the oldest personality system on this atlas by some two thousand
              years, and the only one most people met before they could read -
              which is precisely why it needs the most careful framing.
            </p>
            <p>
              So the framing, stated up front: on this site the signs are read
              as <em>character structures</em> - twelve styles of psychological
              one-sidedness, each with a gift, a trap, and a disowned opposite.
              They are hosted as a language for the psyche, not as a claim
              about the sky. Whether Mars was rising when you were born is a
              question for astronomy, and astronomy has answered it. What the
              figure of the Ram <em>means</em> - initiation, charge, the self
              proven by the first move - is a question for psychology, and it
              is the only question this atlas asks.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              Four Elements, Three Modalities
            </h2>
            <p className="mb-4">
              The wheel is not a list; it is a product. Four elements name{" "}
              <em>what</em> a sign is made of - its native mode of meeting the
              world. Three modalities name <em>how</em> it moves: cardinal
              initiates, fixed sustains, mutable adapts. Cross them and the
              twelve fall out with almost algebraic economy - fire that starts
              (Aries), fire that holds (Leo), fire that travels (Sagittarius),
              and so on around the circle. Few archetypal systems anywhere are
              this cleanly generative.
            </p>
            <div className="grid gap-4 mb-4">
              {ZODIAC_ELEMENTS.map((el) => {
                const signs = getAstrologyByElement(el.id);
                return (
                  <div
                    key={el.id}
                    className="rounded-sm p-5"
                    style={{
                      background: `linear-gradient(145deg, ${el.color}0C, transparent)`,
                      border: `1px solid ${el.color}28`,
                    }}
                  >
                    <div className="flex items-baseline gap-3 mb-2 flex-wrap">
                      <h3
                        className="font-serif text-xl font-medium"
                        style={{ color: el.color }}
                      >
                        {el.label}
                      </h3>
                      <span className="font-mono text-label tracking-label text-muted uppercase">
                        {el.tagline} · {el.temperament}
                      </span>
                      <span
                        className="font-mono text-label tracking-label uppercase ml-auto"
                        style={{ color: el.color + "CC" }}
                      >
                        {el.affectTint}
                      </span>
                    </div>
                    <p className="text-sm mb-3">{el.description}</p>
                    <div className="flex gap-x-4 gap-y-1 flex-wrap">
                      {signs.map((s) => (
                        <span
                          key={s.slug}
                          className="font-serif text-sm inline-flex items-center gap-1.5"
                          style={{ color: el.color }}
                        >
                          <ZodiacGlyph slug={s.slug} color={el.color} size={16} strokeWidth={1.5} className="opacity-80 shrink-0" />
                          {s.name}
                        </span>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
            <p>
              A note on those affect labels. Mapping fire to anger, earth to
              desire, air to fear, and water to shame aligns the elements with
              the affect centers used across this atlas - and it is a{" "}
              <em>structural inference</em>, made here, not a fact recorded in
              any astrological text. The warrant is genealogical: the four
              elements are the same Empedoclean quaternity Jung drew on for his
              four functions (<em>Psychological Types</em>, 1921), and Stephen
              Arroyo carried that correspondence back into astrology
              (<em>Astrology, Psychology and the Four Elements</em>, 1975).
              The alignment is offered because it makes the cross-system
              resonances legible - and flagged because inference dressed as
              tradition is exactly the failure mode this site exists to avoid.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              A Twentieth-Century Retrofit
            </h2>
            <p className="mb-4">
              Here is the fact that makes astrology the most instructive system
              on this atlas: <em>archetypal</em> astrology is not ancient. The
              Hellenistic astrologers cast charts to predict shipwrecks,
              inheritances, and the length of a life; they were fortune-tellers
              with mathematics, not depth psychologists. Astrology learned to
              say &ldquo;archetype&rdquo; only when Dane Rudhyar imported Jung
              wholesale (<em>The Astrology of Personality</em>, 1936),
              recasting the birth chart as a mandala of individuation. Liz
              Greene - a Jungian analyst - completed the translation
              (<em>Saturn: A New Look at an Old Devil</em>, 1976;{" "}
              <em>The Astrology of Fate</em>, 1984), and Richard Tarnas gave it
              its most ambitious statement (<em>Prometheus the Awakener</em>,
              1995; <em>Cosmos and Psyche</em>, 2006).
            </p>
            <p className="mb-4">
              This matters for how you read the resonance map. When the zodiac
              seems to rhyme with the other six systems here - Aries with the
              Hero, Saturn&rsquo;s discipline with the Senex - the rhyme is not
              independent convergence, two traditions arriving at the same
              deep structure from opposite ends of history. It is{" "}
              <em>borrowing</em>. Rudhyar and Greene read Jung and rewrote the
              signs in his vocabulary; the family resemblance runs through a
              citation, not through the collective unconscious. That makes
              astrology the cleanest illustration of this atlas&rsquo;s
              weak-hermeneutic stance: these systems are treated as texts that
              interpret one another, and here the interpretive debt is simply
              a matter of documented record.
            </p>
            <p>
              One caveat cuts deeper still. Tarnas, the most methodologically
              serious of the archetypal astrologers, examined the tradition and
              staked his entire case on the <em>planets</em> - their cycles and
              alignments - because he could find no defensible signal in the
              signs. The zodiac survives in his system as inherited furniture.
              The twelve characters hosted here are, by the admission of their
              own best advocate, the least defended room in astrology&rsquo;s
              house. They are kept anyway, for reasons given below - but you
              should know the floor plan.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              What Jung Actually Said
            </h2>
            <p className="mb-4">
              Jung is routinely conscripted as astrology&rsquo;s character
              witness, so it is worth being precise about his testimony. He
              did call astrology &ldquo;the summation of all the psychological
              knowledge of antiquity&rdquo; (CW 15, 1930) - but the operative
              word is <em>psychological</em>. His account was projection:
              antiquity, lacking a psychology, cast its inner life onto the
              only screen vast enough to hold it. The starry vault, he wrote
              to the astrologer André Barbault in 1954, is the &ldquo;open
              book of cosmic projection&rdquo; - a mirror of the
              mythologems, which is to say the archetypes. On this reading the
              horoscope is a psychological document of enormous antiquity and
              density. It is not a mechanism. Jung nowhere claims the planets
              do anything to anyone.
            </p>
            <p>
              He also ran the experiment. For <em>Synchronicity</em> (1952) he
              collected the charts of hundreds of married couples to test the
              traditional marriage aspects, and reported that the results
              &ldquo;do not exceed&rdquo; what chance would produce - the
              suggestive early runs dissolved as the sample grew. The flickers
              that remained he filed under synchronicity, meaningful
              coincidence, expressly <em>against</em> a causal reading. Jung
              used charts with patients the way he used dreams: as texts to
              interpret. That - no more - is the license this site inherits
              from him, and it is the only license it claims.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              The Claim That Failed
            </h2>
            <p className="mb-4">
              Every other system on this atlas is a hermeneutic - a lens that
              can be more or less illuminating but not, strictly, false.
              Astrology is different: it makes a testable claim about the
              world. The moment of birth is supposed to correlate with
              character. That claim has been tested, carefully and repeatedly,
              and it has failed.
            </p>
            <p className="mb-4">
              The landmark is Shawn Carlson&rsquo;s double-blind study,
              published in <em>Nature</em> in 1985 and designed with the
              cooperation of respected astrologers who approved its protocol
              in advance. Twenty-eight practitioners matched natal charts to
              psychological profiles; they performed at chance, and no better
              on the charts they had flagged as most confident. Geoffrey Dean
              and Ivan Kelly&rsquo;s 2003 study tracked more than 2,000
              &ldquo;time twins&rdquo; - people born minutes apart in London
              in March 1958 - across a hundred-odd measured variables; the
              shared sky produced no shared character. And the Gauquelin
              &ldquo;Mars effect,&rdquo; for decades the skeptics&rsquo; one
              genuine anxiety, collapsed under independent replication into
              selection artifacts.
            </p>
            <p>
              The zodiac&rsquo;s own house is divided besides. The
              precession of the equinoxes has pulled the tropical signs some
              24 degrees off the constellations whose names they carry, so
              the sidereal zodiac of Vedic astrology assigns a great many
              people a different sign altogether. Western and Indian
              astrologers do not agree about what sign anyone <em>is</em> -
              which for an empirical claim would be fatal, and for a symbolic
              language is merely a fact worth knowing. None of this is
              softened here, because the value of everything else on this page
              depends on it being said plainly.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              Why It&rsquo;s Here Anyway
            </h2>
            <p className="mb-4">
              Because a system does not need to be true to be a rich language
              for the psyche. Nobody asks whether the Hero&rsquo;s Journey is{" "}
              <em>true</em>; the question would be a category error. Read the
              same way - as a vocabulary rather than a mechanism - the zodiac
              is one of the oldest and most widely held archetypal languages
              the species possesses: twelve characters, polished by roughly
              two and a half millennia of continuous use, that more living
              humans can name than can name any system psychology has
              produced. A map of archetypal vocabularies that omitted it would
              be dishonest by omission; one that hosted it credulously would
              be dishonest by commission. Reading it beside six other maps,
              with its failures stated on its own about-page, is the only
              honest third option - and it is more respectful than worship,
              because it takes the symbols seriously enough to separate them
              from the claim that could not survive testing.
            </p>
            <p>
              Structurally, the signs enter this site&rsquo;s resonance
              clusters through two documented channels: the Golden Dawn&rsquo;s
              attribution of the twelve signs to the Major Arcana - the bridge
              into Tarot - and the Rudhyar-Greene psychological reading that
              ties them to the Jungian figures. Both are borrowings, both are
              recorded as borrowings, and every astrological link in the
              resonance map is tiered accordingly and carries its dissent. The
              zodiac is a guest here, and it is introduced as one.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-text-primary mb-3 font-medium">
              The Shadow Across the Wheel
            </h2>
            <p>
              Astrology&rsquo;s shadow grammar is its most elegant structural
              feature: a sign&rsquo;s shadow is not a degraded version of
              itself but its <em>opposite across the wheel</em> - the disowned
              half of a shared axis. Aries and Libra split the question of
              self and other; Cancer and Capricorn split hearth and summit;
              each sign is one honest answer to a question whose other honest
              answer sits 180 degrees away. Under pressure, a sign does not
              simply fail - it caricatures its opposite, the Ram turning
              indecisive beneath the bluster, the Crab going cold and
              managerial. Each sign&rsquo;s page reads its opposite as its
              curriculum. How this polarity model compares with the shadow
              structures of the other systems is taken up in{" "}
              <Link
                href="/about/shadow-structures"
                className="text-gold underline underline-offset-2 hover:text-gold/80 transition-colors"
              >
                Shadow Structures
              </Link>
              .
            </p>
          </section>

          <BlindSpotsSection system="astrology" />
        </div>

        <div className="mt-16 text-center animate-slide-up delay-500">
          <Link
            href="/astrology"
            className="inline-flex items-center gap-2 font-mono text-kicker tracking-label text-muted uppercase hover:text-gold transition-colors duration-300"
          >
            <span className="w-6 h-px bg-current" />
            Back to the wheel
            <span className="w-6 h-px bg-current" />
          </Link>
        </div>
      </div>
    </div>
  );
}
